EBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('publisher/', include('publisher.urls')),
    path('customer/', include('customer.urls')),
    path('products/', include('products.urls')),
    path('shopping_cart/', include('shopping_cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    # /general/
    #url('^$', views.LogInView.as_view(), name='index'),
    # /general/login/
    #url('^login$', views.LogInView.as_view(), name='login'),
    # /general/register/
    url(r'^login/$', views.user_login, name='login'),
    url(r'^signup/$', views.register , name='signup'),
    url(r'^logout/$',views.user_logout,name='logout'),
]

website/models.py
from django.db import models
from  django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.mail import send_mail

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    accountType = models.CharField(max_length=20)

    def __self(self):
        return self.user.username

'''
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()'''

def email_new_user(sender, **kwargs):
    if kwargs["created"]:  # only for new users
        new_user = kwargs["instance"]
        print(new_user.email)
        send_mail('Hello From EBook.com', 'Hello there.. Your account is created but not active yet!! Please wait for minimum 30 minutes', 'sandip.kar@iiitb.org',[new_user.email], fail_silently=False)
        send_mail('Hello From EBook.com', new_user.username+' is newly created account!',
                  'sandip.kar@iiitb.org', ['sandipkar.asn@gmail.com'], fail_silently=False)

post_save.connect(email_new_user, sender=User)

website/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import UserProfile

userType = [
    ('Customer','Customer'),
    ('Publisher','Publisher'),
]


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields=['username','email','password1','password2']

class RegistrationForm(forms.ModelForm):
    accountType = forms.CharField(label='Account Type', widget=forms.Select(choices=userType))

    class Meta:
        model = UserProfile
        fields=['accountType']

class LogInForm(AuthenticationForm):
    username = forms.CharField(max_length=500)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

website/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegistrationForm, LogInForm, UserForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .models import UserProfile
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect

def register(request):

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = RegistrationForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user_form.cleaned_data['password1'])
            user.is_active=False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.accountType=request.POST['accountType']
            #user.accountType=request.POST['accountType']
            #print("Hey",user.accountType)
            print(profile.user)
            '''if 'accountType' in request.POST:
                print('HelloSandip')
                profile.accountType=request.POST['accountType']'''
            profile.save()
            print("Success")
            #registered=True
            messages.success(request, f' Account created for!')

            """if accountType=='Customer':
                return redirect('customer:home')
            if accountType == 'Publisher':
                return redirect('publisher:home')"""
    else:
        user_form = UserForm()
        profile_form = RegistrationForm()
    return render(request, 'website/register.html', {'user_form':user_form,'profile_form':profile_form})



def user_login(request):
    if request.method == "POST":
        login_form = LogInForm(data=request.POST)
        # profile_form = RegistrationForm(data=request.POST)
        if login_form.is_valid:
            username = request.POST.get('username')
            password = request.POST.get('password')
            # accountType = request.POST.get('accountType')
            user = authenticate(username=username, password=password)
            if user:
                print('is active or not..!!')
                if user.is_active:
                    print('Active ')
                    accountType=UserProfile.objects.get(user_id=user.id).accountType
                    # if(UserProfile.objects.get(user_id=user.id).accountType==accountType):
                    login(request, user)
                    if(accountType=='Publisher'):
                        return redirect('publisher:home')
                    if(accountType=='Customer'):
                        return redirect('products:product-list')
                else:
                    messages.error(request, "Your account is not active yet..!!")
            else:
                print('credential part..!!')
                messages.error(request,"Your account is not active yet..!!")
        else:
            messages.error(request,"Login Form is not valid!!")
            return render(request, "website/login.html", {'login_form' : login_form})
    else:
        login_form = LogInForm()
        # profile_form = RegistrationForm()
    return render(request, "website/login.html",{'login_form':login_form})


@login_required
def user_logout(request):
    logout(request)
    messages.info(request,"Logged  Out Successfully.!!")
    return HttpResponseRedirect(reverse('website:login'))

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link  rel="icon" type="image/x-icon" href="{%static 'publisher/images/icon.png'%}"/>
    <title>{% block title %}CustomEBook{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'publisher/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}&nbsp;&nbsp;<a class="ml-2" href="{% url 'website:login' %}">Sign In</a>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}
</body>
</html>

website/templates/website/login.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load staticfiles %}
<div class="form-container">
  <div class="row">
    <div class="center-block col-md-6" style="float: none;">
        <form method="POST">
            {% csrf_token %}
            <center><img src="{% static 'publisher/images/icon.png'%}"/></center>
                <legend class="border-bottom mb-4"> <center>Custom Ebook</center></legend>
                {{ login_form|crispy }}
            <div class="form-group">
                <button class="btn btn-success" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <form method="get" action="{% url 'website:signup' %}">
                New To Custom Ebook?
                <button class="btn btn-success" type="submit">SignUp</button>
            </form>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

website/templates/website/register.html
{% extends "website/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load staticfiles %}

<div class="form-container">
  <div class="row">
    <div class="center-block col-md-6" style="float: none;">
        <form method="POST">
            {% csrf_token %}
            <center><img src="{% static 'publisher/images/icon.png'%}"/></center>
            <legend class="border-bottom mb-4"> <center>Custom Ebook</center></legend>
            {{ user_form|crispy }}
            {{ profile_form|crispy }}

            <div class="form-group">
                <button class="btn btn-success" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account?<a class="ml-2" href="{% url 'website:login' %}">Sign In</a>
            </small>
        </div>
    </div>
   </div>
</div>
{% endblock content %}