EBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('publisher/', include('publisher.urls')),
    path('customer/', include('customer.urls')),
    path('products/', include('products.urls')),
    path('shopping_cart/', include('shopping_cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.conf.urls import url
from . import views


app_name = 'customer'
urlpatterns = [
    # /customer/
     url(r'^$', views.home , name='home'),
     url(r'^buy/$', views.Buy , name='buy'),
     url(r'^pay/$', views.Pay, name='pay'),
     url(r'^payConfirm/$', views.PayConfirm, name='payConfirm'),
     url(r'^orderhistory/$', views.orderHistory, name='order_history'),
     url(r'^(?P<pk>[0-9]+)/orderdelete/$', views.OrderDelete.as_view(), name='orderDelete'),
     url(r'^search/$', views.search , name='search'),
     url(r'^(?P<pk>[0-9]+)/OrderItemDelete/$',views.OrderItemDelete.as_view(),name='OrderItemDelete'),

    # url(r'^(?P<pk>[0-9]+)/chaptersdetails/$', views.ChapterDetailView.as_view(), name='chapter-details'),

    # url(r'^cart/$', views.AddToCart.as_view(), name='cart-add'),

]

products/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/chaptersdetails/$', views.chapter_details, name='chapterdetails'),

]

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records, name='update_records'),
]

website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    # /general/
    #url('^$', views.LogInView.as_view(), name='index'),
    # /general/login/
    #url('^login$', views.LogInView.as_view(), name='login'),
    # /general/register/
    url(r'^login/$', views.user_login, name='login'),
    url(r'^signup/$', views.register , name='signup'),
    url(r'^logout/$',views.user_logout,name='logout'),
]

customer/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from products.models import Chapter


class CustomerProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    chapters = models.ManyToManyField(Chapter, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    user_profile, created = CustomerProfile.objects.get_or_create(user=instance)
    user_profile.save()

post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

customer/views.py
from django.http import HttpResponse
from django.views import generic
from .models import CustomerProfile
from products.models  import EBook,Chapter
from django.shortcuts import render, get_object_or_404
from shopping_cart.models import Order
from publisher.script import pdf_cat, make_Introduction
from django.shortcuts import render, redirect
from django.urls import reverse
import requests
from shopping_cart.models import OrderItem
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.conf import settings
from django.db import transaction
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
import json

@login_required()
def home(request):
    my_user_profile = CustomerProfile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=False, owner=my_user_profile)
    print(my_orders)
    if(my_orders):
        order=my_orders.get(owner=my_user_profile).items.all()
        print(order)
        sum=0
        for items in order:
            sum+=items.product.price
        context = {
            'my_orders': my_orders,
            'sum': sum,
        }
        return render(request, "customer/home.html", context)
    else:
        return render(request, "customer/home.html")

@login_required()
def Buy(request):
    ref_no=request.GET.get('ref_no')
    print(ref_no)
    return render(request, "customer/payment.html",{'ref_no':ref_no})

@login_required()
def PayConfirm(request):
    return render(request, "customer/Payment_confirm.html")


def insertOrUpdate(model):
    try:
        with transaction.atomic():
            model.save()
    except IntegrityError as e:
        return HttpResponse('')


@login_required()
def orderHistory(request):
    my_user_profile = CustomerProfile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
    print(my_orders)
    return render(request, "customer/Order_history.html",{'my_orders':my_orders})

@login_required()
def Pay(request):
    name_book=request.POST.get('book_name')
    print('book_name: ',name_book)
    product_ids=json.loads(request.POST.get('id'))
    print('productIds: ',product_ids)
    my_user_profile = CustomerProfile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=False, owner=my_user_profile)
    ref_no=0
    for order in my_orders:
        print("My order: ", order)
        ref_no=order.ref_code
        order.is_ordered=True
        order.save()
        insertOrUpdate(order)
    my_orders = Order.objects.filter(is_ordered=False, owner=my_user_profile)
    print("2nd My order: ", my_orders)
    # eBooks = EBook.objects.all()
    # chapters = Chapter.objects.all()
    ebooks_url=[]
    introduction_set=[]
    introduction=['Book_Name', 'Chapter_Name', 'Page_No']
    introduction_set.append(introduction)
    count = 2
    intro_url=settings.MEDIA_ROOT + '\\' +'simple_table.pdf'
    ebooks_url.append(intro_url)
    for id in product_ids:
        print(id)
        introduction = []
        ebook=Chapter.objects.get(id=id).ebook
        chapter = Chapter.objects.get(id=id)
        url=ebook.bookurl
        start_page=chapter.start_page
        end_page = chapter.end_page
        book_name=ebook.bookpdf.name.replace('.pdf','_')
        chapter_name=chapter.name
        chapter_url=url+'\\'+book_name+chapter_name+'.pdf'
        introduction.append(ebook.title)
        introduction.append(chapter_name)
        introduction.append(str(count))
        introduction_set.append(introduction)
        count+=(end_page-start_page+1)
        ebooks_url.append(chapter_url)
    print(introduction_set)
    print(ebooks_url)
    make_Introduction(name_book,introduction_set)
    pdf_cat(ref_no,ebooks_url)
    return HttpResponse(ref_no)



class OrderItemDelete(DeleteView):
    model = OrderItem
    success_url = reverse_lazy('customer:home')


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('customer:home')



def search(request):
    if request.method == 'POST':
        book_name =  request.POST.get('search')
        print(book_name)
        status = EBook.objects.none()
        try:
            title = EBook.objects.filter(title__icontains=book_name)
            if (not (status)):
                genre = EBook.objects.filter(genre__icontains=book_name)
                print(genre)
            else:
                genre = EBook.objects.filter(genre__icontains=book_name)

            if(not (status)):
                keyword = EBook.objects.filter(keyword__icontains=book_name)
                print(keyword)
            else:
                keyword = EBook.objects.filter(keyword__icontains=book_name)
            status= title|genre|keyword
            print(status)
            # if(not(status)):
            #     status = EBook.objects.filter(genre__icontains=book_name)
            # if (not(status)):
            #     status = EBook.objects.filter(keyword__icontains=book_name)
            #Add_prod class contains a column called 'bookname'
        except EBook.DoesNotExist:
            status = None
        return render(request,"customer/search.html",{"ebook_list":status})
    else:
        return render(request,"customer/search.html")

customer/templates/customer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link  rel="icon" type="image/x-icon" href="{%static 'publisher/images/icon.png'%}"/>
   <!-- <link rel="icon" href="http://www.domain.com/favicon.ico" type="image/x-icon" />-->
    <!--<link  rel="icon" type="image/png" src="{%static 'publisher/images/logo.png'%}"/>-->
    <title>{% block title %}EBook{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'publisher/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'publisher/pay_style.css' %}"/>
    <script src="{% static 'publisher/detail.js' %}"></script>
    <script src="{% static 'publisher/easyResponsiveTabs.js' %}"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'products:product-list' %}">Ebook</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'products:product-list' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbspEBooks
                    </a>
                </li>
                <!--<li class="">-->
                    <!--<a href="{% url 'customer:home' %}">-->
                        <!--<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp{{ request.user }}-->
                    <!--</a>-->
                <!--</li>-->
            </ul>
            <ul class="nav navbar-nav">
            <form class="navbar-form navbar-left" role="search" method="POST" action="{% url 'customer:search' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="search" value="">
                </div>
                <button type="submit" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;Search
                </button>
            </form>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span>&nbsp{{ request.user }}
                        <!--<span class="caret"></span>-->
                    </button>
                    <ul class="nav navbar-nav dropdown-menu">
                        <li class="">
                            <a href="{% url 'customer:home' %}">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'customer:order_history' %}">
                                <span class="glyphicon glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;order_history
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'website:logout' %}">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                            </a>
                        </li>
                    </ul>
                </div>
                <!--<ul class="nav navbar-nav navbar-right">-->
                    <!--<li class="">-->
                        <!--<a href="{% url 'customer:home' %}">-->
                            <!--<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;Cart-->
                        <!--</a>-->
                    <!--</li>-->
                    <!--<li class="">-->
                        <!--<a href="{% url 'website:logout' %}">-->
                            <!--<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout-->
                        <!--</a>-->
                    <!--</li>-->
            </ul>
        </div>
        </div>

</nav>
    {% block body %}
    {% endblock %}
</body>
</html>

customer/templates/customer/home.html
{% extends 'customer/base.html' %}
{% block body %}
    {{ message }}
<div class="main">
{% if my_orders %}
<div class="form-container">
    <div class="row">
    {% for order in my_orders %}
            <div class="center-block col-md-15" style="float: none;">
                <h1>Order Summary</h1>
                <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table" id="tableID">
                        <thead>
                            <tr>
                                <th>Book Name</th>
                                <th>Chapter Name</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for items in order.items.all %}
                            <tr id="{{items.product.id}}">
                                <td>
                                    {{ items.product.ebook }}
                                </td>
                                <td>
                                    {{ items.product.name }}
                                </td>
                                <td>
                                    {{ items.product.price }}
                                </td>
                                <td>

                                    <form action="{% url 'customer:OrderItemDelete' items.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete?');"  class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                    </form>

                                </td>
                                <td>
                                    <button type="submit" class="btn up btn-default btn-sm"><span class="glyphicon glyphicon-arrow-up" enabled></span></button>
                                    <button type="submit" class="btn down btn-default btn-sm"><span class="glyphicon glyphicon-arrow-down" enabled></span></button>
                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                    <script>
                        var x = document.getElementById("tableID").rows.length;
                        var ctr = 1
                        $("#tableID tbody tr").each(function (key, value) {

                            if (ctr == 1)
                            {
                                $(this).find('.up').attr('disabled','disabled');
                            }
                            if (ctr == x-1)
                            {
                                $(this).find('.down').attr('disabled','disabled');
                            }
                            ctr++;
                        });
                </script>
                    <div class="text-right">
                        <p>Total: {{sum}}</p>

                    <form method="POST">
                        {% csrf_token %}
                        <div style="float: left;">
                                <h3>Book Name:</h3>
                            </div>
                                <input type="text" class="form-control" id='book_name' name="book_name"  placeholder="Enter your book name"/>
                             <br>

                        <a onClick="pay(this.id)" id="{{order.ref_code}}" class="btn btn-primary pay-btn"><span class="glyphicon glyphicon-triangle-right"></span>Pay Now</a>
                    </form>
                    </div>
                </div>
                </div>


                <!--{% if order in user.profile.ebooks.all %}
                &lt;!&ndash; add a button here to see the product &ndash;&gt;
                You own this
                {% elif object in current_order_products %}
                <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                {% else %}

                {% endif %}
                <br><br>-->

            </div>
    {% endfor %}
    </div>
</div>
{% else %}
    <h3> Your Cart is Empty..!!</h3>

{% endif%}
<!--<p class="footer">Copyright © Group 5 DS 603/DM 2019 Order Summary Widget. All Rights Reserved | Template by <a href="http://localhost:8000/customer/" target="_blank">Custom EBook</a></p>-->
<!--<br>-->
</div>
{% endblock %}

customer/templates/customer/payment.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% extends 'customer/base.html' %}
<html>
<head>
	{% load staticfiles %}
<title>Payment Form Widget Flat Responsive Widget Template :: w3layouts</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Payment Form Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />-->
<link href='//fonts.googleapis.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Alegreya+Sans:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<script type="text/javascript"  src="{% static 'publisher/jquery.min.js' %}"></script>
</head>
{% block body %}

<body>
	<div class="main">
		<h1>Payment Form</h1>
		<div class="content">


					<script type="text/javascript">
						$(document).ready(function () {
							$('#horizontalTab').easyResponsiveTabs({
								type: 'default', //Types: default, vertical, accordion
								width: 'auto', //auto or any width like 600px
								fit: true   // 100% fit in a container
							});
						});

					</script>
						<div class="sap_tabs">
							<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
								<div class="pay-tabs">
									<h2>Select Payment Method</h2>
									  <ul class="resp-tabs-list">
										  <li class="resp-tab-item" aria-controls="tab_item-0" role="tab"><span><label class="pic1"></label>Credit Card</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-1" role="tab"><span><label class="pic3"></label>Net Banking</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-2" role="tab"><span><label class="pic4"></label>PayPal</span></li>
										  <li class="resp-tab-item" aria-controls="tab_item-3" role="tab"><span><label class="pic2"></label>Debit Card</span></li>
										  <div class="clear"></div>
									  </ul>
								</div>
								<div class="resp-tabs-container">
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
										<div class="payment-info">
											<!--<h3>Personal Information</h3>
											<form>
												<div class="tab-for">
													<h5>EMAIL ADDRESS</h5>
														<input type="text" value="abc@gmail.com">
													<h5>FIRST NAME</h5>
														<input type="text" value="ABC">
												</div>
											</form>-->
											<h3 class="pay-title">Credit Card Info</h3>
											<form action="{% url 'customer:payConfirm' %}" method="post">
												{% csrf_token %}
												<div class="tab-for">
													<h5>NAME ON CARD</h5>
														<input type="text" value="ABCXYZ">
													<h5>CARD NUMBER</h5>
														<input type="text" value="8340-0430-4560-0900" >
													<!--class="pay-logo"  onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '0000-0000-0000-0000';}" required=""-->
												</div>
												<div class="transaction">
													<div class="tab-form-left user-form">
														<h5>EXPIRATION</h5>
															<ul>
																<li>
																	<input type="number" class="text_box" type="text" value="6" min="1" />
																</li>
																<li>
																	<input type="number" class="text_box" type="text" value="1988" min="1" />
																</li>

															</ul>
													</div>
													<div class="tab-form-right user-form-rt">
														<h5>CVV NUMBER</h5>
														<input type="text" value="123" >
														<!--onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'xxxx';}" required=""-->
													</div>
													<div class="clear"></div>
												</div>
												<div class="single-bottom">
													<ul>
														<li>
															<input type="checkbox"  id="brand" value="">
															<label for="brand"><span></span>By checking this box, I agree to the Terms & Conditions & Privacy Policy.</label>
														</li>
													</ul>
											</div>
												<br>

												<br>
												<input onclick="download(this.id)" id="{{ref_no}}" type="submit" value="SUBMIT">
											</form>

										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-1">
										<div class="payment-info">
											<h3>Net Banking</h3>
											<div class="radio-btns">
												<div class="swit">
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio" checked=""><i></i>Andhra Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Allahabad Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Bank of Baroda</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Canara Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>IDBI Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Icici Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Indian Overseas Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Punjab National Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>South Indian Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>State Bank Of India</label> </div></div>
												</div>
												<div class="swit">
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio" checked=""><i></i>City Union Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>HDFC Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>IndusInd Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Syndicate Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Deutsche Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Corporation Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>UCO Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Indian Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>Federal Bank</label> </div></div>
													<div class="check_box"> <div class="radio"> <label><input type="radio" name="radio"><i></i>ING Vysya Bank</label> </div></div>
												</div>
												<div class="clear"></div>
											</div>
											<form action="{% url 'customer:payConfirm'%}" method="post">
												{% csrf_token %}
											<a onclick="download(this.id)" id="{{ref_no}}" type="submit">Continue</a>
											</form>
										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-2">
										<div class="payment-info">
											<h3>PayPal</h3>
											<h4>Already Have A PayPal Account?</h4>
											<div class="login-tab">
												<div class="user-login">
													<h2>Login</h2>

													<form action="{% url 'customer:payConfirm'%}" method="post">
														{% csrf_token %}
														<input type="text" value="name@email.com" >
														<!--onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'name@email.com';}" required=""-->
														<input type="password" value="PASSWORD" >
														<!--onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}" required=""-->
															<div class="user-grids">
																<div class="user-left">
																	<div class="single-bottom">
																			<ul>
																				<li>
																					<input type="checkbox"  id="brand1" value="">
																					<label for="brand1"><span></span>Remember me?</label>
																				</li>
																			</ul>
																	</div>
																</div>
																<div class="user-right">
																	<input onclick="download(this.id)" id="{{ref_no}}"	 type="submit" value="LOGIN">
																</div>
																<div class="clear"></div>
															</div>
													</form>
												</div>
											</div>
										</div>
									</div>
									<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-3">
										<div class="payment-info">

											<h3 class="pay-title">Dedit Card Info</h3>
											<form action="{% url 'customer:payConfirm'%}" method="post">
												{% csrf_token %}
												<div class="tab-for">
													<h5>NAME ON CARD</h5>
														<input type="text" value="ABCXYZ">
													<h5>CARD NUMBER</h5>
														<input  type="text" value="8000-8000-8000-9003" >
													<!--class="pay-logo" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '0000-0000-0000-0000';}" required=""-->
												</div>
												<div class="transaction">
													<div class="tab-form-left user-form">
														<h5>EXPIRATION</h5>
															<ul>
																<li>
																	<input type="number" class="text_box" type="text" value="6" min="1" />
																</li>
																<li>
																	<input type="number" class="text_box" type="text" value="1988" min="1" />
																</li>

															</ul>
													</div>
													<div class="tab-form-right user-form-rt">
														<h5>CVV NUMBER</h5>
														<input type="text" value="231">
														 <!--onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'xxxx';}" required=""-->
													</div>
													<div class="clear"></div>
												</div>
												<div class="single-bottom">
													<ul>
														<li>
															<input type="checkbox"  id="brand" value="">
															<label for="brand"><span></span>By checking this box, I agree to the Terms & Conditions & Privacy Policy.</label>
														</li>
													</ul>
											</div>
												<br></br>
												<input onclick="download(this.id)" id="{{ref_no}}" type="submit" value="SUBMIT">

											</form>

										</div>
									</div>
								</div>
							</div>
						</div>

		</div>
		<p class="footer">Copyright © Group 5 DS 603/DM 2019 Payment Form Widget. All Rights Reserved | Template by <a href="http://localhost:8000/customer/pay/" target="_blank">Custom EBook</a></p>
	</div>
</body>
{% endblock %}

</html>

customer/templates/customer/search.html
{% extends 'customer/base.html' %}
{% block body %}
<div class="container-fluid">
    {% if ebook_list %}
      {% for ebook in ebook_list %}
    <div class="col-xs-4 col-md-2">
    <div class="thumbnail">
        <div class="center-block" style="float: none;">
            <!-- Album logo -->
            <a href="{% url 'products:chapterdetails' ebook.pk %}">
                <img src="{{ ebook.ebook_logo.url }}" class="img-responsive">
            </a>
            <!--<div class="col-md-2" style="float: none;">
                <h2>{{ ebook.title }}</h2>
                <h4>{{ ebook.author }}</h4>
                <h4>{{ ebook.genre }}</h4>
            </div>-->
            <!-- Details -->
            <form action="" method="post" style="display: inline;">
                {% csrf_token %}
            <a href="{% url 'products:chapterdetails' ebook.pk %}" class="btn btn-primary btn-sm">View Chapters</a>
            </form>
            </div>
         </div>

    </div>
    {% endfor %}
    {% else %}
        <h3> Sorry! No Book Available According To your Choice!</h3>
  {% endif %}
</div>
{% endblock %}