EBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('publisher/', include('publisher.urls')),
    path('customer/', include('customer.urls')),
    path('products/', include('products.urls')),
    path('shopping_cart/', include('shopping_cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publisher/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'publisher'


urlpatterns = [
    # /publisher/
    url(r'^$', views.home, name='home'),

    # /publisher/album/add/
    url(r'^add/$', login_required(views.EBookCreate.as_view()), name='ebook-add'),

    url(r'^search/$', views.search , name='search'),

    url(r'^(?P<pk>[0-9]+)/chapters/$', views.createChapters, name='chapter-add'),

    url(r'^(?P<pk>[0-9]+)/chaptersCSV/$', views.createChaptersUsingCSV, name='chapter-add-csv'),

    url(r'^(?P<pk>[0-9]+)/chaptersdetails/$', login_required(views.ChapterDetailView.as_view()), name='chapter-details'),

    url(r'publisher/(?P<pk>[0-9]+)/chaptersdelete/$', login_required(views.ChapterDelete.as_view()), name='chapter-delete'),


    # /publisher/album/2/
    url(r'publisher/(?P<pk>[0-9]+)/$', login_required(views.EBookUpdate.as_view()), name='ebook-update'),

    # /publisher/album/2/delete/
    url(r'publisher/(?P<pk>[0-9]+)/delete/$', login_required(views.EBookDelete.as_view()), name='ebook-delete'),
]

website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    # /general/
    #url('^$', views.LogInView.as_view(), name='index'),
    # /general/login/
    #url('^login$', views.LogInView.as_view(), name='login'),
    # /general/register/
    url(r'^login/$', views.user_login, name='login'),
    url(r'^signup/$', views.register , name='signup'),
    url(r'^logout/$',views.user_logout,name='logout'),
]

products/models.py
from django.db import models
from django.urls import reverse
import datetime
from django.conf import settings
from django.contrib.auth.models import User


class EBook(models.Model):
    title = models.CharField(max_length=500)
    author = models.CharField(max_length=500)
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    published_date = models.DateField(default=datetime.date.today)
    genre = models.CharField(max_length=100)
    keyword = models.CharField(max_length=1000, null=True)
    ebook_logo = models.FileField()
    bookpdf = models.FileField(blank=True, null=True)
    bookurl = models.CharField(max_length=500, default=settings.MEDIA_ROOT)
    ebook_price = models.DecimalField(max_digits=100, decimal_places=2)

    def get_absolute_url(self):
        return reverse('publisher:chapter-details', kwargs={'pk' : self.pk})

    def __str__(self):
        return self.title

    def _get_file(self):
        self._require_file()
        if not hasattr(self, '_file') or self._file is None:
            self._file = self.storage.open(self.bookpdf, 'rb')
        return self._file


class Chapter(models.Model):
    ebook = models.ForeignKey(EBook, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    description = models.CharField(max_length=2000)
    start_page = models.IntegerField()
    end_page = models.IntegerField()
    price = models.DecimalField(max_digits=100, decimal_places=2)

publisher/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from products.models import EBook

class PublisherProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ebooks = models.ManyToManyField(EBook, blank=True)

    def __str__(self):
        return self.user.username


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    user_profile, created = PublisherProfile.objects.get_or_create(user=instance)
    user_profile.save()

post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

publisher/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render_to_response
from django.shortcuts import render,redirect
from products.models import EBook, Chapter
from products.forms import MyForm, MyChapterForm
from django.http import HttpResponse
from .script import pdf_splitter
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404

from shopping_cart.models import Order
from .models import PublisherProfile
from django.contrib.auth.models import User
import csv
import io
# class HomeView(generic.ListView):
#     template_name = "publisher/home.html"
#     context_object_name = "object_list"
#     def get_queryset(self):
#         return EBook.objects.all()



class ChapterDetailView(generic.ListView):
    template_name = "publisher/chapterDetail.html"
    context_object_name = "ebook"
    def get_queryset(self):
        my_user_profile = PublisherProfile.objects.filter(user=self.request.user).first()
        user = User.objects.filter(username=my_user_profile).first()
        ebooks = EBook.objects.filter(publisher=user)
        return ebooks.get(id=self.kwargs.get('pk'))


class EBookCreate(CreateView):
    form_class = MyForm
    def form_valid(self, form):
        form.instance.publisher = self.request.user
        return super(EBookCreate, self).form_valid(form)
    template_name = "publisher/ebook_form.html"
    success_url = reverse_lazy('publisher:home')

@login_required()
def createChapters(request, pk):
    print(request.POST)
    chapter_form = MyChapterForm()
    if request.method == 'POST':
        print("success")
        chapter_form = MyChapterForm(data=request.POST)
        if chapter_form.is_valid:
            print("hello")
            start_page = request.POST.get('start_page')
            end_page = request.POST.get('end_page')
            chapter_name=request.POST.get('name')
            c_id=pk
            print(c_id,type(c_id))
            book_name=str(EBook.objects.get(id=c_id).bookpdf.name)
            chapter = chapter_form.save(commit=False)
            chapter.ebook = EBook.objects.get(id=c_id)
            chapter.save()
            url_name=EBook.objects.get(id=c_id).bookurl
            print(url_name+'\\'+book_name)
            ebook=url_name+'\\'+book_name
            print('Type:', type(ebook))
            print(ebook)
            pdf_splitter(ebook,start_page,end_page,chapter_name,book_name)

    else:
        chapter_form = MyChapterForm()
    return render(request, 'publisher/createchapters.html', {'form':chapter_form,'pk':pk})

login_required
def createChaptersUsingCSV(request, pk):
    print(pk)
    file_name=request.FILES['fileToUpload']
    print(type(file_name))
    ebook=EBook.objects.get(id=pk)
    my_user_profile = PublisherProfile.objects.filter(user=request.user).first()
    user = User.objects.filter(username=my_user_profile).first()
    ebook = EBook.objects.filter(publisher=user).get(id=pk)
    context = {
        'ebook': ebook
    }
    file_name.seek(0)
    reader = csv.DictReader(io.StringIO(file_name.read().decode('utf-8')))
    for row in reader:
        book_name = str(EBook.objects.get(id=pk).bookpdf.name)
        url_name = EBook.objects.get(id=pk).bookurl
        ebook_url = url_name + '\\' + book_name
        start_page=row['start_page']
        end_page = row['end_page']
        chapter_name=row['name']
        pdf_splitter(ebook_url, start_page, end_page, chapter_name, book_name)
        p = Chapter(ebook=ebook,name=row['name'], description=row['description'],start_page=row['start_page'],end_page=row['end_page'],price=row['price'])
        p.save()
    return render(request,"publisher/chapterDetail.html",context)


@login_required()
def home(request):
    my_user_profile = PublisherProfile.objects.filter(user=request.user).first()
    user=User.objects.filter(username = my_user_profile).first()
    ebooks = EBook.objects.filter(publisher=user)
    context = {
		'ebooks': ebooks
	}
    return render(request, "publisher/home.html", context)


class EBookUpdate(UpdateView):
    model = EBook
    fields = '__all__'


class EBookDelete(DeleteView):
    model = EBook
    success_url = reverse_lazy('publisher:home')



class ChapterDelete(DeleteView):
    model = Chapter
    def get_success_url(self):
        pk=self.kwargs['pk']
        ebook=Chapter.objects.get(id=pk).ebook.title
        ebook_pk = EBook.objects.filter(title=ebook)[0].id
        return reverse_lazy('publisher:chapter-details', kwargs={'pk': ebook_pk})


@login_required()
def search(request):
    if request.method == 'POST':
        book_name =  request.POST.get('search')
        print(book_name)
        try:
            status = EBook.objects.filter(title__icontains=book_name)
            #Add_prod class contains a column called 'bookname'
        except EBook.DoesNotExist:
            status = None
        return render(request,"publisher/search.html",{"ebook_list":status})
    else:
        return render(request,"publisher/search.html")

publisher/templates/publisher/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link  rel="icon" type="image/x-icon" href="{%static 'publisher/images/icon.png'%}"/>
   <!-- <link rel="icon" href="http://www.domain.com/favicon.ico" type="image/x-icon" />-->
    <!--<link  rel="icon" type="image/png" src="{%static 'publisher/images/logo.png'%}"/>-->
    <title>{% block title %}EBook{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'publisher/style.css' %}"/>
    <script src="{% static 'publisher/detail.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'publisher:home' %}">Ebook</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'publisher:home' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbspEBooks
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="POST" action="{% url 'publisher:search' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="search" value="">
                </div>
                <button type="submit" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;Search
                </button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'publisher:ebook-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add EBook
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'publisher:home' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp{{ request.user }}
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'website:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>
        </div>
        </div>

</nav>
    {% block body %}
    {% endblock %}
</body>
</html>

publisher/templates/publisher/chapterDetail.html
{% extends 'publisher/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book Details{% endblock %}
{% block ebook_active %}active{% endblock %}
{% block body %}
<div class="chapter-container container-fluid">
    {% if ebook %}
    <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'publisher:home'%}">
                            <img src="{{ ebook.ebook_logo.url }}" alt="ebook_logo" class="img-responsive">
                        </a>
                        <h1>{{ ebook.title }}
                            <small>{{ ebook.genre }}</small>
                        </h1>
                        <h2>{{ ebook.publisher }} </h2>
                    </div>
                </div>
            </div>
        <div class="col-sm-4 col-md-8">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>All Chapters</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Chapter Name</th>
                                <th>Description</th>
                                <th>Start Page</th>
                                <th>End Page</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for chapter in ebook.chapter_set.all %}
                            <tr>
                                <td>
                                    {{chapter.name}}
                                </td>
                                <td>
                                    {{chapter.description}}
                                </td>
                                <td>
                                    {{chapter.start_page}}
                                </td>
                                <td>
                                    {{chapter.end_page}}
                                </td>
                                <td>
                                    {{chapter.price}}
                                </td>
                                <td>
                                    <form action="{% url 'publisher:chapter-delete' chapter.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="chapter_id" value="{{ chapter.id }}"/>
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-default btn-sm">
                                        <span  class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <h3> You don't have any seperated chapters </h3>
    {% endif %}
</div>
{% endblock %}

publisher/templates/publisher/createchapters.html
{% extends 'publisher/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Book Details{% endblock %}
{% block ebook_active %}active{% endblock %}
{% block body %}
{{errors}}
<div class="form-container">
  <div class="row">
    <div class="center-block col-md-6" style="float: none;">

  <form method="POST">
      {% csrf_token %}
         <legend class="title">Add Chapters</legend>
          {{ form|crispy }}

      <div class="form-group">
        <button id="submit" name="submit" class="btn btn-success btn-md">Submit</button>
        <a onClick="myFunction()" class="btn btn-warning btn-md">
        <span class="glyphicon glyphicon-plus"></span>AddMore
        </a>
          <a  class="btn btn-warning btn-md upload-btn">
        <span class="glyphicon glyphicon-plus"></span>Upload CSV
        </a>
        <a href="{% url 'publisher:home'%}" class="btn btn-primary btn-sm">Back</a>
      </div>
    </form>
        <form id="fileUpload" action="{%url 'publisher:chapter-add-csv' pk%}" method="POST" enctype="multipart/form-data">
         {% csrf_token %}
            Select csv to upload:
            <input type="file" name="fileToUpload" id="fileToUpload">
            <input type="submit" value="Upload CSV" name="submit" class="btn btn-success btn-md">
        </form>
      </div>
  </div>
</div>
{% endblock %}

publisher/templates/publisher/ebook_form.html
{% extends 'publisher/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add a New Book{% endblock %}
{% block body %}
<div class="form-container">
    <div class="row">
    <div class="center-block col-md-6" style="float: none;">
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <legend class="title">ADD EBook</legend>
            {{ form|crispy }}

                <!--<div class="col-sm-offset-2 col-sm-10">-->
                    <button type="submit" class="btn btn-success">Submit</button>
                <!--</div>-->

        </form>
    </div>
    </div>
</div>
{% endblock %}

publisher/templates/publisher/home.html
{% extends 'publisher/base.html' %}


{% block body %}
<div class="ebook-container container-fluid">
    {% if ebooks %}

            {% for ebook in ebooks %}
<div class="thumbnail">
              <div class="row">

                <div class="col-sm-2">
                    <!-- Album logo -->
                    <a href="{% url 'publisher:chapter-details' ebook.id%}">
                        <img src="{{ ebook.ebook_logo.url }}" class="img-responsive">
                    </a>
                </div>
                <div class="col-sm-10">
                    <div class="caption">
                        <h2>{{ ebook.title }}</h2>
                        <h4>{{ ebook.author }}</h4>
                        <h4>{{ ebook.genre }}</h4>
                    </div>

                    <!-- Details -->

                    <form action="" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="ebook_id" value="{{ ebook.id }}"/>
                    <a href="{% url 'publisher:chapter-add' ebook.id %}" class="btn btn-primary btn-sm">Add Chapters</a>
                    <a href="{% url 'publisher:chapter-details' ebook.id %}" class="btn btn-primary btn-sm">View Chapters</a>
                    </form>
                    <!-- Delete -->
                    <form action="{% url 'publisher:ebook-delete' ebook.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="ebook_id" value="{{ ebook.id }}"/>
                        <button type="submit" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-default btn-sm delete_button">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                    </div>
                 </div>
    </div>
            {% endfor %}
    {% else %}
        <h3> You don't have any Book</h3>

  {% endif %}

</div>
{% endblock %}

publisher/templates/publisher/search.html
{% extends 'publisher/base.html' %}
{% block body %}
<div class="container-fluid">
    {% if ebook_list %}
      {% for ebook in ebook_list %}
    <div class="col-xs-4 col-md-2">
    <div class="thumbnail">
        <div class="center-block" style="float: none;">
            <!-- Album logo -->
            <a href="{% url 'publisher:chapter-details' ebook.pk %}">
                <img src="{{ ebook.ebook_logo.url }}" class="img-responsive">
            </a>
            <!--<div class="col-md-2" style="float: none;">
                <h2>{{ ebook.title }}</h2>
                <h4>{{ ebook.author }}</h4>
                <h4>{{ ebook.genre }}</h4>
            </div>-->
            <!-- Details -->
            <form action="" method="post" style="display: inline;">
                {% csrf_token %}
            <a href="{% url 'publisher:chapter-details' ebook.pk %}" class="btn btn-primary btn-sm">View Chapters</a>
            </form>
            </div>
         </div>

    </div>
    {% endfor %}
    {% else %}
        <h3> Sorry! No Book Available According To your Choice!</h3>
  {% endif %}
</div>
{% endblock %}